---
title: "Моделирование геополей"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mapview)
library(fields)
library(raster)
library(stars)
library(sf)
library(rnaturalearth)
```

## Загрузка исходных данных

```{r}
tab = read_csv('argo.csv')
pts = st_as_sf(tab, coords = c('Long', 'Lat'), crs = 4326) %>% 
  st_transform(3395)
mapview(pts)
# plot(pts)
```

## Построение сетки

```{r}
box = st_bbox(pts)
# envelope = box[c(1,3,2,4)]

px_grid = st_as_stars(box, dx = 50000, dy = 50000)

ggplot() +
  geom_sf(data = st_as_sf(px_grid)) +
  geom_sf(data = pts)
```

## Интерполяция

```{r}
coords = st_coordinates(pts)
coords_grid = st_coordinates(px_grid)
pred = Tps(coords, pts$Sal, scale.type = 'unscaled') # Модель для солености

# После этого можно интерполировать значения с помощью функции predict():
px_grid = px_grid %>% 
  mutate(sal_tps = predict(pred, coords_grid))

plot(px_grid['sal_tps'])
```

Загрузка полигона океана:
```{r}
ocean = ne_download(scale = 50, 
                    type = 'ocean', 
                    category = 'physical',
                    returnclass = 'sf')

land = ne_download(scale = 50, 
                    type = 'land', 
                    category = 'physical',
                    returnclass = 'sf')

ocean_merc = ocean %>% 
  st_cast('POLYGON') %>% 
  st_transform(3395)

land_merc = land %>% 
  st_cast('POLYGON') %>% 
  st_transform(3395)
```
## Обрезка растра
```{r}
# маскирование растра и обрезка океана
px_grid_crop = px_grid[ocean_merc]
ocean_crop = st_crop(ocean_merc, box)
land_crop = st_crop(land_merc, box)
```

## Визуализация

```{r}
sal_breaks = seq(33, 38.5, by = 0.5)
sal_ncolors = length(sal_breaks) - 1

grat = st_graticule(box)

cont_tps = st_contour(px_grid_crop['sal_tps'], 
                      breaks = sal_breaks, 
                      contour_lines = TRUE)
## Старый GDAL
# rast = stars:::st_as_raster(px_grid_crop['sal_tps'])
# cont_tps = raster::rasterToContour(rast, levels = sal_breaks) %>% 
#   st_as_sf()

sal_colors = colorRampPalette(c('white', 'yellow', 
                                'red', 'darkred'))

ggplot() +
  geom_stars(data = cut(px_grid_crop['sal_tps'], 
                        breaks = sal_breaks)) +
  scale_fill_manual(name = '‰',
                    values = sal_colors(sal_ncolors),
                    guide = guide_legend(label.vjust = -0.3, 
                                         reverse = TRUE, 
                                         title.position = "bottom"),
                    labels = sal_breaks,
                    na.value = 'white',
                    drop = FALSE) +
  geom_sf(data = cont_tps) + 
  geom_sf(data = ocean_crop, fill = NA, color = 'blue') +
  geom_sf(data = land_crop, fill = 'lightgray') +
  geom_sf(data = pts) +
  geom_sf(data = grat, size = 0.2, linetype = 3) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  theme_bw() +
  theme()
  labs(title = 'Соленость')
```



